package com.mindmatrix.hallisanthedigital.ui.auth

import android.content.Intent
import android.os.Bundle
import android.view.View
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.mindmatrix.hallisanthedigital.R
import com.mindmatrix.hallisanthedigital.databinding.ActivityLoginBinding
import com.mindmatrix.hallisanthedigital.ui.home.BuyerHomeActivity
import com.mindmatrix.hallisanthedigital.ui.home.SellerDashboardActivity

class LoginActivity : AppCompatActivity() {

    private lateinit var binding: ActivityLoginBinding
    private lateinit var auth: FirebaseAuth
    private lateinit var googleSignInClient: GoogleSignInClient
    private val db = FirebaseFirestore.getInstance()

    companion object {
        const val RC_SIGN_IN = 9001
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityLoginBinding.inflate(layoutInflater)
        setContentView(binding.root)

        auth = FirebaseAuth.getInstance()

        if (auth.currentUser != null) {
            routeByRole()
            return
        }

        setupGoogleSignIn()

        binding.btnLogin.setOnClickListener { loginWithEmail() }
        binding.btnGoogleSignIn.setOnClickListener { signInWithGoogle() }
        binding.tvSignup.setOnClickListener {
            startActivity(Intent(this, SignupActivity::class.java))
        }
        binding.tvForgotPassword.setOnClickListener { forgotPassword() }
    }

    private fun setupGoogleSignIn() {
        // ✅ Using R.string.default_web_client_id is safer than hardcoding
        // This ID is generated by the google-services plugin during build
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id))
            .requestEmail()
            .build()
        googleSignInClient = GoogleSignIn.getClient(this, gso)
    }

    private fun loginWithEmail() {
        val email = binding.etEmail.text.toString().trim()
        val password = binding.etPassword.text.toString().trim()

        if (email.isEmpty() || password.isEmpty()) {
            Toast.makeText(this, "Please enter email and password", Toast.LENGTH_SHORT).show()
            return
        }

        showLoading(true)
        auth.signInWithEmailAndPassword(email, password)
            .addOnSuccessListener { routeByRole() }
            .addOnFailureListener {
                showLoading(false)
                Toast.makeText(this, "Login failed: ${it.message}", Toast.LENGTH_SHORT).show()
            }
    }

    private fun signInWithGoogle() {
        val signInIntent = googleSignInClient.signInIntent
        startActivityForResult(signInIntent, RC_SIGN_IN)
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == RC_SIGN_IN) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            try {
                val account = task.getResult(ApiException::class.java)
                firebaseAuthWithGoogle(account.idToken!!)
            } catch (e: ApiException) {
                // Error 10 will appear here if SHA-1 is missing in Firebase
                Toast.makeText(this, "Google sign-in failed: ${e.statusCode} - ${e.message}", Toast.LENGTH_LONG).show()
            }
        }
    }

    private fun firebaseAuthWithGoogle(idToken: String) {
        showLoading(true)
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        auth.signInWithCredential(credential)
            .addOnSuccessListener { result ->
                val user = result.user ?: return@addOnSuccessListener
                val isNew = result.additionalUserInfo?.isNewUser == true
                if (isNew) {
                    val intent = Intent(this, SignupActivity::class.java).apply {
                        putExtra("googleName", user.displayName ?: "")
                        putExtra("googleEmail", user.email ?: "")
                        putExtra("isGoogleUser", true)
                    }
                    startActivity(intent)
                    finish()
                } else {
                    routeByRole()
                }
            }
            .addOnFailureListener {
                showLoading(false)
                Toast.makeText(this, "Auth failed: ${it.message}", Toast.LENGTH_SHORT).show()
            }
    }

    private fun routeByRole() {
        val uid = auth.currentUser?.uid ?: return
        showLoading(true)

        db.collection("users").document(uid).get()
            .addOnSuccessListener { document ->
                showLoading(false)
                val role = document.getString("role") ?: "buyer"
                if (role == "seller") {
                    startActivity(Intent(this, SellerDashboardActivity::class.java))
                } else {
                    startActivity(Intent(this, BuyerHomeActivity::class.java))
                }
                finish()
            }
            .addOnFailureListener {
                showLoading(false)
                startActivity(Intent(this, BuyerHomeActivity::class.java))
                finish()
            }
    }

    private fun forgotPassword() {
        val email = binding.etEmail.text.toString().trim()
        if (email.isEmpty()) {
            Toast.makeText(this, "Enter your email first", Toast.LENGTH_SHORT).show()
            return
        }
        auth.sendPasswordResetEmail(email)
            .addOnSuccessListener {
                Toast.makeText(this, "Reset email sent to $email", Toast.LENGTH_SHORT).show()
            }
            .addOnFailureListener {
                Toast.makeText(this, "Failed: ${it.message}", Toast.LENGTH_SHORT).show()
            }
    }

    private fun showLoading(show: Boolean) {
        binding.progressBar.visibility = if (show) View.VISIBLE else View.GONE
        binding.btnLogin.isEnabled = !show
        binding.btnGoogleSignIn.isEnabled = !show
    }
}